version: 2.1
orbs:
  node: circleci/node@5.0.2
# Define the jobs we want to run for this project
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm install install
      - run: npm install gulp
      - run: npm install mocha
      - run: ls -l
      - persist_to_workspace:
          root: ./
          paths:
            - ./node_modules
  unittest:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ./node_modules
      - run: ls -l
      - run: ls -l ./node_modules
      - run: "npx gulp build"
      - run: "npx mocha \"./dist/**/test/unit/**/*.spec.js\""

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
      - unittest:
          requires:
            - build