version: 2.1
orbs:
  node: circleci/node@5.0.2
# Define the jobs we want to run for this project
jobs:
  build:
    steps:
      - run: ls -l
      - run: npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build