version: 2.1
orbs:
  node: circleci/node@5.0.2
# Define the jobs we want to run for this project
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: node_modules_cache
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run: npm install gulp
      - run: npm install mocha
      - run: ls -l
      - save_cache:
          key: node_mod
          paths:
            -  ./node_modules
  unittest:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: node_mod
      - run: ls -l
      - run: "npx gulp build"
      - run: "npx mocha \"./dist/**/test/unit/**/*.spec.js\""

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
      - unittest:
          requires:
            - build