version: 2.1
orbs:
  node: circleci/node@5.0.2
# Define the jobs we want to run for this project
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm install gulp
      - run: sudo npm install -g gulp
      - run: "gulp unit"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - unit-test