version: 2.1
orbs:
  node: circleci/node@5.0.2
# Define the jobs we want to run for this project
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm install gulp
  unittest:
    executor: node/default
    steps:
      - checkout
      - run: "gulp build"
      - run: "mocha "./dist/**/test/unit/**/*.spec.js""

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
      - unittest:
          requires:
            - build